Gauss Elimination Method

In [ ]:
import numpy as np
# coefficient matrix
a=np.array([[1,2,3],[2,-1,1],[3,0,-1]],float)
# constant matrix
b=np.array([9,8,3],float)
print(a)
print(b)
n=len(a)
# Applying Gauss Elimination
for i in range (n-1):
  for j in range (i+1,n):
    if a[j,i]==0: continue
    factor=a[j,i]/a[i,i]
    for k in range (i,n):
      a[j,k]=a[j,k]-a[i,k]*factor
    b[j]=b[j]-b[i]*factor
print(a)
print(b)
x = np.zeros(n)
print(x)
# Back Substitution
x[n-1] = b[n-1]/a[n-1][n-1]

for i in range(n-2,-1,-1):
    sum=0

    for j in range(i+1,n):
        sum = sum+a[i,j]*x[j]
    x[i]=(b[i]-sum)/a[i,i]
print(x)

# Displaying solution
print('\nRequired solution is: ')
for i in range(n):
    print('X%d = %0.2f' %(i,x[i]), end = '\t')

[[ 1.  2.  3.]
 [ 2. -1.  1.]
 [ 3.  0. -1.]]
[9. 8. 3.]
[[ 1.  2.  3.]
 [ 0. -5. -5.]
 [ 0.  0. -4.]]
[  9. -10. -12.]
[0. 0. 0.]
[ 2. -1.  3.]

Required solution is: 
X0 = 2.00	X1 = -1.00	X2 = 3.00	

In [ ]:
import numpy as np
# coefficient matrix
a=np.array([[1,2,3],[2,-1,1],[3,0,-1]],float)
# constant matrix
b=np.array([9,8,3],float)
print(a)
print(b)
n=len(a)
# Applying Gauss Elimination
for i in range (n-1):
  for j in range (i+1,n):
    if a[j,i]==0: continue
    factor=a[i,i]/a[j,i]
    for k in range (i,n):
      a[j,k]=a[j,k]*factor-a[i,k]
    b[j]=b[j]*factor-b[i]
print(a)
print(b)
x = np.zeros(n)
print(x)
# Back Substitution
x[n-1] = b[n-1]/a[n-1][n-1]

for i in range(n-2,-1,-1):
    sum=0

    for j in range(i+1,n):
        sum = sum+a[i,j]*x[j]
    x[i]=(b[i]-sum)/a[i,i]
print(x)

# Displaying solution
print('\nRequired solution is: ')
for i in range(n):
    print('X%d = %0.2f' %(i,x[i]), end = '\t')

[[ 1.  2.  3.]
 [ 2. -1.  1.]
 [ 3.  0. -1.]]
[9. 8. 3.]
[[ 1.          2.          3.        ]
 [ 0.         -2.5        -2.5       ]
 [ 0.          0.         -1.66666667]]
[ 9. -5. -5.]
[0. 0. 0.]
[ 2. -1.  3.]

Required solution is: 
X0 = 2.00	X1 = -1.00	X2 = 3.00	

In [ ]:
import numpy as np
# Augmented matrix
a=np.array([[4,3,-5,2],[-4,-5,7,-4],[8,6,-8,6]],float)
print(a)
n=len(a)
print(n)
# Applying Gauss Elimination
for i in range (n-1):
  for j in range (i+1,n):
    if a[j,i]==0: continue
    factor=a[i,i]/a[j,i]
    for k in range (i,n+1):
      a[j,k]=a[j,k]*factor-a[i,k]
print(a)
x = np.zeros(n)
print(x)
# Back Substitution
x[n-1] = a[n-1,n]/a[n-1,n-1]

for i in range(n-2,-1,-1):
    sum=0
    for j in range(i+1,n):
        sum = sum+a[i,j]*x[j]
    x[i]=(a[i,j+1]-sum)/a[i,i]
print(x)

# Displaying solution
print('\nRequired solution is: ')
for i in range(n):
    print('X%d = %0.2f' %(i,x[i]), end = '\t')

[[ 4.  3. -5.  2.]
 [-4. -5.  7. -4.]
 [ 8.  6. -8.  6.]]
3
[[ 4.  3. -5.  2.]
 [ 0.  2. -2.  2.]
 [ 0.  0.  1.  1.]]
[0. 0. 0.]
[0.25 2.   1.  ]

Required solution is: 
X0 = 0.25	X1 = 2.00	X2 = 1.00	