# Augmented Matrix of Linear system of equations

In [ ]:
import sympy as sp

# Define the symbolic variables
x1, x2 = sp.symbols('x1 x2')

# Define the coefficient matrix A and the right-hand side vector b
A = sp.Matrix([[2, 3], [4, 1]])  # Coefficient matrix (2x2)
b = sp.Matrix([5, 6])            # Right-hand side vector (2x1)

# Construct the augmented matrix [A|b]
augmented_matrix = A.row_join(b)

# Display the augmented matrix
print("Augmented Matrix [A|b]:")
sp.pprint(augmented_matrix)

Augmented Matrix [A|b]:
⎡2  3  5⎤
⎢       ⎥
⎣4  1  6⎦


#Row echelon form of linear system of equations

In [ ]:
import sympy as sp

def row_echelon_form(A):
    # Get the number of rows and columns in the matrix A
    rows, cols = A.shape

    # Perform row operations to achieve row echelon form
    row = 0  # Start from the first row
    for col in range(cols - 1):  # Ignore the last column (b vector in augmented matrix)
        if row >= rows:
            break

        # Find the pivot in the current column (the first non-zero element in this column)
        if A[row, col] == 0:
            # If the pivot is zero, swap the current row with a row below it that has a non-zero element in this column
            for i in range(row + 1, rows):
                if A[i, col] != 0:
                    A.row_swap(row, i)
                    break

        # Eliminate the entries below the pivot in the current column
        for i in range(row + 1, rows):
            if A[i, col] != 0:
                A[i, :] = A[i, :] - (A[i, col]/A[col,col]) * A[row, :]
                print(A[i,:])

        # Move to the next row
        row += 1

    return A

# Example augmented matrix [A|b]
A = sp.Matrix([
    [1, 2, 3, 9],
    [2, 3, 1, 8],
    [3, 4, 2, 7]
])

# Display the matrix before row reduction
print("Original augmented matrix:")
sp.pprint(A)

# Convert to Row Echelon Form (REF)
REF_A = row_echelon_form(A)

# Display the Row Echelon Form (REF) matrix
print("\nRow Echelon Form (REF) of the augmented matrix:")
sp.pprint(REF_A)


Original augmented matrix:
⎡1  2  3  9⎤
⎢          ⎥
⎢2  3  1  8⎥
⎢          ⎥
⎣3  4  2  7⎦
Matrix([[0, -1, -5, -10]])
Matrix([[0, -2, -7, -20]])
Matrix([[0, 0, 3, 0]])

Row Echelon Form (REF) of the augmented matrix:
⎡1  2   3    9 ⎤
⎢              ⎥
⎢0  -1  -5  -10⎥
⎢              ⎥
⎣0  0   3    0 ⎦


#One more code to find row ehelon form of a matrix

In [ ]:
import numpy as np
# Function to check if matrix is in REF

def is_row_echelon_form(matrix):
	if not matrix.any():
		return False

	rows = matrix.shape[0]
	cols = matrix.shape[1]
	prev_leading_col = -1

	for row in range(rows):
		leading_col_found = False
		for col in range(cols):
			if matrix[row, col] != 0:
				if col <= prev_leading_col:
					return False
				prev_leading_col = col
				leading_col_found = True
				break
		if not leading_col_found and any(matrix[row, col] != 0 for col in range(cols)):
			return False
	return True

def find_nonzero_row(matrix, pivot_row, col):
	nrows = matrix.shape[0]
	for row in range(pivot_row, nrows):
		if matrix[row, col] != 0:
			return row
	return None

# Swapping rows so that we can have our non zero row on the top of the matrix
def swap_rows(matrix, row1, row2):
	matrix[[row1, row2]] = matrix[[row2, row1]]

def make_pivot_one(matrix, pivot_row, col):
	pivot_element = matrix[pivot_row, col]
	matrix[pivot_row] //= pivot_element
	# print(pivot_element)

def eliminate_below(matrix, pivot_row, col):
	nrows = matrix.shape[0]
	pivot_element = matrix[pivot_row, col]
	for row in range(pivot_row + 1, nrows):
		factor = matrix[row, col]
		matrix[row] -= factor * matrix[pivot_row]

# Implementing above functions
def row_echelon_form(matrix):
	nrows = matrix.shape[0]
	ncols = matrix.shape[1]
	pivot_row = 0
# this will run for number of column times. If matrix has 3 columns this loop will run for 3 times
	for col in range(ncols):
		nonzero_row = find_nonzero_row(matrix, pivot_row, col)
		if nonzero_row is not None:
			swap_rows(matrix, pivot_row, nonzero_row)
			make_pivot_one(matrix, pivot_row, col)
			eliminate_below(matrix, pivot_row, col)
			pivot_row += 1
	return matrix


matrix = np.array([[3,-2,4,-2],[2,1,10,7],[-4,4,-8,4],[4,-1,14,6]])
print("Matrix Before Converting:")
print(matrix)
print()
result = row_echelon_form(matrix)
print("After Converting to Row Echelon Form:")
print(result)
if is_row_echelon_form(result):
	print("In REF")
else:
	print("Not in REF--------------->")


Matrix Before Converting:
[[ 3 -2  4 -2]
 [ 2  1 10  7]
 [-4  4 -8  4]
 [ 4 -1 14  6]]

After Converting to Row Echelon Form:
[[ 1 -1  1 -1]
 [ 0  1  2  3]
 [ 0  0  1  0]
 [ 0  0  0  1]]
In REF


# Row reduced echelon form

In [ ]:
import sympy as sp

# Define the symbolic variables
x1, x2 = sp.symbols('x1 x2')

# Define the coefficient matrix A and the right-hand side vector b
A = sp.Matrix([[2, 3], [4, 1]])  # Coefficient matrix (2x2)
b = sp.Matrix([5, 6])            # Right-hand side vector (2x1)

# Construct the augmented matrix [A|b]
augmented_matrix = A.row_join(b)

# Display the augmented matrix
print("Augmented Matrix [A|b]:")
sp.pprint(augmented_matrix)

# Compute the Row reduced Echelon Form (RREF) of the augmented matrix
RREF_matrix, pivot_columns = augmented_matrix.rref()

# Display the Row Reduced Echelon Form (RREF)
print("\nRow Echelon Form (RREF) of the augmented matrix:")
sp.pprint(RREF_matrix)

Augmented Matrix [A|b]:
⎡2  3  5⎤
⎢       ⎥
⎣4  1  6⎦

Row Echelon Form (RREF) of the augmented matrix:
⎡      13 ⎤
⎢1  0  ── ⎥
⎢      10 ⎥
⎢         ⎥
⎣0  1  4/5⎦


#To creat a function "check_consistency" to check consistency

In [1]:
import numpy as np
from scipy.linalg import solve


def check_consistency(A, b):
    # Combine the coefficient matrix A and the constant matrix B
    AB = np.hstack((A, b.reshape(-1, 1)))
    print(AB)

    # To find rank of the matrix
    rank_A = np.linalg.matrix_rank(A)
    print("The rank of a Matrix A",rank_A)
    rank_AB = np.linalg.matrix_rank(AB)
    print("The rank of a Matrix AB",rank_AB)
    print("no of unknowns",len(A))
    if rank_A==rank_AB:
      print("The system in consistent")
      if rank_A==len(A):
        print("The system has uniqe solution")
        x = solve(A, b)
      else:
        x="The system has infinitely Many solution"
    else:
      x="The system is inconsistent"
      return x
x = np.array([[0, 1, 1],
              [1, 1, 0],
              [1, 0, 1]])
y = np.array([3.65, 1.55, 0])
check_consistency(x, y)

[[0.   1.   1.   3.65]
 [1.   1.   0.   1.55]
 [1.   0.   1.   0.  ]]
The rank of a Matrix A 3
The rank of a Matrix AB 3
no of unknowns 3
The system in consistent
The system has uniqe solution


# solve linear system of equation Ax=B

In [ ]:

from sympy import symbols, simplify
from sympy.matrices import Matrix
import sympy
c, d, e = symbols("c, d, e")
A = Matrix([[1,2,3], [2, 3,5],[2, 3,6]])
sympy.pprint(A)
b = Matrix([c, d,e])
AB= A.row_join(b)
sympy.pprint(AB)
if A.rank()==AB.rank():
  if sympy.det(A)!=0:
    x1,x2,x3 = A.solve(b)
    print(f"The required uniqe solution is\nx1={x1}\nx2={x2}\nx3={x3}")
  else:
    print("It has infinitely many solution")
else:
  print("The system has no solution")

⎡1  2  3⎤
⎢       ⎥
⎢2  3  5⎥
⎢       ⎥
⎣2  3  6⎦
⎡1  2  3  c⎤
⎢          ⎥
⎢2  3  5  d⎥
⎢          ⎥
⎣2  3  6  e⎦
The required uniqe solution is
x1=-3*c + 3*d - e
x2=2*c - e
x3=-d + e


# Gauss Eliminiation Mathod


In [ ]:
import numpy as np
# coefficient matrix
a=np.array([[1,2,3],[1,2,1],[0,1,-1]],float)
# constant matrix
b=np.array([9,8,3],float)
print(f"coefficient matrix is {a}")
print("")
print(f"constant matrix is {b}")
print("")
n=np.shape(a)[0]
print(f"number of unknowns {n}")
print("")
# Applying Gauss Elimination
if  np.linalg.det(a)==0:
  print("Gauss elimination method can not be applied")
else:
  for i in range (n-1):
    if (a[i,i]==0):
      for j in range (i+1,n):
        if  (a[j,i]!=0):
          a[[i,j]]=a[[j,i]]
        else:
         continue
    else:
      for j in range (i+1,n):
        if a[j,i]==0: continue
        factor=a[j,i]/a[i,i]
        for k in range (i,n):
          a[j,k]=a[j,k]-a[i,k]*factor
        b[j]=b[j]-b[i]*factor
print(f" Upper triangular matrix of coefficient matrix\n {a}")
print(f" Updated matrix of the constant matrix {b}")
print("")
x = np.zeros(n)
print(f"initial values for unknowns {x}")
print("")
#Back Substitution
print("Back Substitution")
x[n-1] = b[n-1]/a[n-1][n-1]

for i in range(n-2,-1,-1):
    sum=0

    for j in range(i+1,n):
        sum = sum+a[i,j]*x[j]
    x[i]=(b[i]-sum)/a[i,i]

# Displaying solution
print('\nRequired solution after applying back substitution is: ')
for i in range(n):
    print('X%d = %0.2f' %(i,x[i]), end = '\t')

coefficient matrix is [[ 1.  2.  3.]
 [ 1.  2.  1.]
 [ 0.  1. -1.]]

constant matrix is [9. 8. 3.]

number of unknowns 3

 Upper triangular matrix of coefficient matrix
 [[ 1.  2.  3.]
 [ 0.  1. -1.]
 [ 0.  0. -2.]]
 Updated matrix of the constant matrix [ 9. -1.  3.]

initial values for unknowns [0. 0. 0.]

Back Substitution

Required solution after applying back substitution is: 
X0 = 18.50	X1 = -2.50	X2 = -1.50	

#Gauss elimination input as augmented matrix

In [ ]:
import numpy as np
# Augmented matrix
a=np.array([[4,3,-5,2],[-4,-5,7,-4],[8,6,-8,6]],float)
print(f"Augmented matrix is\n{a}")
n=len(a)
print(f"The number of row are \n{n}")
# Applying Gauss Elimination
for i in range (n-1):
  for j in range (i+1,n):
    if a[j,i]==0: continue
    factor=a[i,i]/a[j,i]
    for k in range (i,n+1):
      a[j,k]=a[j,k]*factor-a[i,k]
print(f"Upper triangular matrix of augmented matrix \n{a}")
x = np.zeros(n)
print(f"The Initial approximation of x {x}")
# Back Substitution
x[n-1] = a[n-1,n]/a[n-1,n-1]

for i in range(n-2,-1,-1):
    sum=0
    for j in range(i+1,n):
        sum = sum+a[i,j]*x[j]
    x[i]=(a[i,j+1]-sum)/a[i,i]

# Displaying solution
print('\nRequired solution is: ')
for i in range(n):
    print('X%d = %0.2f' %(i,x[i]), end = '\t')

Augmented matrix is
[[ 4.  3. -5.  2.]
 [-4. -5.  7. -4.]
 [ 8.  6. -8.  6.]]
The number of row are 
3
Upper triangular matrix of augmented matrix 
[[ 4.  3. -5.  2.]
 [ 0.  2. -2.  2.]
 [ 0.  0.  1.  1.]]
The Initial approximation of x [0. 0. 0.]

Required solution is: 
X0 = 0.25	X1 = 2.00	X2 = 1.00	

#Gauss Jordan Mathod

In [ ]:
import sympy as sp

# Define the symbolic variables
x1, x2 = sp.symbols('x1 x2')

# Define the coefficient matrix A and the right-hand side vector b
A = sp.Matrix([[2, 3], [4, 1]])  # Coefficient matrix (2x2)
b = sp.Matrix([5, 6])            # Right-hand side vector (2x1)

# Construct the augmented matrix [A|b]
augmented_matrix = A.row_join(b)

# Display the augmented matrix
print("Augmented Matrix [A|b]:")
sp.pprint(augmented_matrix)

# Compute the Row reduced Echelon Form (RREF) of the augmented matrix
RREF_matrix, pivot_columns = augmented_matrix.rref()

# Display the Row Reduced Echelon Form (RREF)
print("\nRow Reduced Echelon Form (RREF) of the augmented matrix:")
sp.pprint(RREF_matrix)

#The solution is
for i in range(len(RREF_matrix[:,-1])):
  print(f"The solutions are x{i}={RREF_matrix[:,-1][i]}")

Augmented Matrix [A|b]:
⎡2  3  5⎤
⎢       ⎥
⎣4  1  6⎦

Row Reduced Echelon Form (RREF) of the augmented matrix:
⎡      13 ⎤
⎢1  0  ── ⎥
⎢      10 ⎥
⎢         ⎥
⎣0  1  4/5⎦
The solutions are x0=13/10
The solutions are x1=4/5
