
# Orthogonal vectors and orthonormal vectors

In [ ]:
import numpy as np
vectors = [
    [1, 0, 0],
    [0, 2, 0]
]
# Calculate the dot product of vectors[0] and vectors[1]
dot_product = np.dot(vectors[0], vectors[1])
print(f"The dot product between two vectors is {dot_product}")
# Calculate the length of vectors[0] and vectors[1]
norm_v0=np.linalg.norm(vectors[0])
print(f"The length of the vector {vectors[0]} is {norm_v0}")
norm_v1=np.linalg.norm(vectors[1])
print(f"The length of the vector {vectors[1]} is {norm_v1}")
if dot_product==0:
  if norm_v0==norm_v1==1:
    print(" The given two vectors are orthogonal and orthonormal")
  else:
    print(" The given two vectors are orthogonal but length of one vector is not 1 so not orthonormal")
else:
  if norm_v0==norm_v1==1:
    print(" The length of given two vectors are 1 but dot product is not zero so not are orthogonal hence not orthonormal")
  else:
    print(" The length of the a vector in vectors are not 1 and also dot product is not zero so not are orthogonal hence not orthonormal")

The dot product between two vectors is 0
The length of the vector [1, 0, 0] is 1.0
The length of the vector [0, 2, 0] is 2.0
 The given two vectors are orthogonal but length of one vector is not 1 so not orthonormal


# Orthogonal set

In [ ]:
import numpy as np

def is_orthogonalset(vectors):
    # Convert the list of vectors into a numpy array
    vectors = np.array(vectors)

    # Iterate through every pair of vectors
    for i in range(len(vectors)):
        for j in range(i + 1, len(vectors)):
            # Calculate the dot product of vectors[i] and vectors[j]
            dot_product = np.dot(vectors[i], vectors[j])
            if not np.isclose(dot_product, 0):
                return False  # The vectors are not orthogonal

    # If all dot products are zero, the vectors are orthogonal
    return True

# For example:
vectors = [
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 2]
]

if is_orthogonalset(vectors):
    print("The set of vectors is orthogonal.")
else:
    print("The set of vectors is not orthogonal.")


The set of vectors is orthogonal.


# Orthonormal set only

In [ ]:
import numpy as np

def is_orthonormal_set(vectors):
    # Convert the list of vectors into a numpy array
    vectors = np.array(vectors)

    # Iterate through every pair of vectors
    for i in range(len(vectors)):
        for j in range(i + 1, len(vectors)):
            # Calculate the dot product of vectors[i] and vectors[j]
            dot_product = np.dot(vectors[i], vectors[j])
            norm_vi=np.linalg.norm(vectors[i])
            norm_vj=np.linalg.norm(vectors[j])
            if dot_product!=0 or norm_vi!=1 or norm_vj!=1:
                return False  # The vectors are not orthogonal

    # If all dot products are zero, the vectors are orthogonal
    return True

# For example:
vectors = [
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 2]
]

if is_orthonormal_set(vectors):
    print("The set of vectors is orthonormal.")
else:
    print("The set of vectors is not orthonormal.")

The set of vectors is not orthonormal.


#Orthogonal and  Orthonormal set together

In [ ]:
import numpy as np

def is_orthonormalset(vectors):
    # Convert the list of vectors into a numpy array
    vectors = np.array(vectors)
    orthogonalset=is_orthogonalset(vectors)
    if orthogonalset==True:
      # Iterate through every pair of vectors
      for i in range(len(vectors)):
        norm_vi=np.linalg.norm(vectors[i])
        if (norm_vi!=1):
          return False  # The vectors are not orthogonal

    # If all dot products are zero, the vectors are orthogonal
    return True

# For example:
vectors = [
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 2]
]

if is_orthogonalset(vectors):
    #print("The set of vectors is orthogonal set.")
    if not is_orthonormalset(vectors):
      print("The set of vectors is orthogonal but not orthonormal set.")
    else:
      print("The set of vectors orthogonal set and orthonormal set.")
else:
     print("The set of vectors neither orthogonal set not orthonormal set.")


The set of vectors is orthogonal but not orthonormal set.


#orthogonal basis using function orthogonalset

In [ ]:
import numpy as np

def is_orthogonalset(vectors):
    # Convert the list of vectors into a numpy array
    vectors = np.array(vectors)

    # Iterate through every pair of vectors
    for i in range(len(vectors)):
        for j in range(i + 1, len(vectors)):
            # Calculate the dot product of vectors[i] and vectors[j]
            dot_product = np.dot(vectors[i], vectors[j])
            if not np.isclose(dot_product, 0):
                return False  # The vectors are not orthogonal

    # If all dot products are zero, the vectors are orthogonal
    return True

# For example:
vectors = [
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
]

if is_orthogonalset(vectors):
    print("The set of vectors is orthogonal.")
else:
    print("The set of vectors is not orthogonal.")

The set of vectors is orthogonal.


In [ ]:
import numpy as np
def IsOrthogonalBasis(vectors):
  # Checking wether the set is orthogonal set for which we are using the previous fuction
  if is_orthogonalset(vectors):
    print("The set is linear independent")
    if len(vectors)==len(vectors[0]):
      x="and it spans the vector space V. Hence it forms orthogonal basis for vector space"
    else:
      x="and it spans the subspace W of vector space V. Hence it forms orthogonal basis for subspace"
  else:
    x="The set is not orhtogonal basis"
  return x
# For example:
vectors = [
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 0]
]
print(f" The followings are the vector set {vectors}")
IsOrthogonalBasis(vectors)

 The followings are the vector set [[1, 0, 0], [0, 1, 0], [0, 0, 0]]
The set is linear independent


'and it spans the vector space V. Hence it forms orthogonal basis for vector space'

#orthonormal basis

In [ ]:
import numpy as np
def IsOrthonormalBasis(vectors):
  # Checking wether the set is orthogonal set for which we are using the previous fuction
  if is_orthonormal_set(vectors):
    print("The set is linear independent")
    if len(vectors)==len(vectors[0]):
      x="and it spans the vector space V. Hence it forms orthonormal basis for vector space"
    else:
      x="and it spans the subspace W of vector space V. Hence it forms orthonormal basis for subspace"
  else:
    x="The set is not orthonormal basis"
  return x
# For example:
vectors = [
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
]
print(f" The followings are the vector set {vectors}")
IsOrthonormalBasis(vectors)

 The followings are the vector set [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
The set is linear independent


'and it spans the vector space V. Hence it forms orthonormal basis for vector space'

#The set of vectors which are orthogonal to the given set of vectors
(Orthogonal complement)

In [ ]:
import numpy as np
from scipy.linalg import null_space
def orthonormalcomplement(vectors):
  vectors== np.array([u1,u2])
  x = null_space(A)
  return x
u1=[1,1,1]
u2=[1,1,1]
A = np.array([u1,u2])
x=orthonormalcomplement(A)
print(f"the given set of vectors\n {A}")
print(f"the set of vectors which are orthogonal to the given a set of vectors is\n {x}")
print(f" product of A and x is\n {np.dot(A,x)}")

the given set of vectors
 [[1 1 1]
 [1 1 1]]
the set of vectors which are orthogonal to the given a set of vectors is
 [[-0.81649658  0.        ]
 [ 0.40824829 -0.70710678]
 [ 0.40824829  0.70710678]]
 product of A and x is
 [[-1.11022302e-16  0.00000000e+00]
 [-1.11022302e-16  0.00000000e+00]]


#Projection of y on u

In [ ]:
import numpy as np
def proj(y,u):
  # Convert the list of vectors into a numpy array
  y= np.array(y)
  u= np.array(u)
  proj_y=(np.dot(y, u)/np.dot(u, u))*u
  return proj_y
# For example:
u=[1,3,4]
print(f" The vector u is {u}")
y=[1,2,3]
print(f" The given vector y is {y}")
print(f"The projection of y on a set of vectors is {proj(y,u)}")




 The vector u is [1, 3, 4]
 The given vector y is [1, 2, 3]
The projection of y on a set of vectors is [0.73076923 2.19230769 2.92307692]


#Projection of y on {u1,u2,....u3}

In [ ]:
def proj_of_y(y,vectors):
    total_proj = 0.0
    for i in range(len(vectors)):
        total_proj += proj(y, vectors[i])  # Accumulate projections here
    return total_proj
# For example:
vectors = [
    [1, 0, 0],
    [2, 1, 3],
    [1, 0, 2]
]
print(f" The followings are the vector set {vectors}")
y=[1,2,3]
print(f" The given vector y {y}")
print(f"The projection of y on a set of vectors is {proj_of_y(y,vectors)}")


 The followings are the vector set [[1, 0, 0], [2, 1, 3], [1, 0, 2]]
 The given vector y [1, 2, 3]
The projection of y on a set of vectors is [4.25714286 0.92857143 5.58571429]


#Least square method and least squre error

In [ ]:
import numpy as np
from scipy.linalg import lstsq
A = [[1, 1, 0 ,0],[1,1,0,0],[1,0,1,0],[1,0,1,0],[1,0,0,1],[1,0,0,1]]
b=[-3,-1,0,2,5,1]
p, res, rnk, s = lstsq(A, b)
print(f"The matrix A is {A} and b is {b}")
print(f"The least square solution for Ax=b is {p}")
print(f"the least error is {np.sqrt(res)}")

The matrix A is [[1, 1, 0, 0], [1, 1, 0, 0], [1, 0, 1, 0], [1, 0, 1, 0], [1, 0, 0, 1], [1, 0, 0, 1]] and b is [-3, -1, 0, 2, 5, 1]
The least square solution for Ax=b is [ 0.5 -2.5  0.5  2.5]
the least error is []


In [ ]:
import numpy as np
from scipy.linalg import lstsq
A = [[4,0],
    [0, 2],
    [1, 1]]
b=[2,0,11]
print(f"The matrix A is {A} and b is {b}")
p, res, rnk, s = lstsq(A, b)
print(f"The least square solution for Ax=b is {p}")
print(f"the least error is {np.sqrt(res)}")

The matrix A is [[4, 0], [0, 2], [1, 1]] and b is [2, 0, 11]
The least square solution for Ax=b is [1. 2.]
the least error is 9.165151389911681


#Projection Matrix of a1 and a2

In [ ]:
import numpy as np
from numpy.linalg import inv
def calc_proj_matrix(A):
    ATA=np.dot(A.T,A)
    ATA_inv=np.linalg.inv(ATA)
    AdotATA_inv=np.dot(A,ATA_inv)
    P=np.dot(AdotATA_inv,A.T)
    return P
a1=[1,0,1]
a2=[1,1,1]
B=np.vstack([a1,a2]).T
print(f"The matrix A is {B} and shape of a matrix {np.shape(B)}")
print(f"(The projection of A is P= {calc_proj_matrix(B)}")

The matrix A is [[1 1]
 [0 1]
 [1 1]] and shape of a matrix (3, 2)
(The projection of A is P= [[0.5 0.  0.5]
 [0.  1.  0. ]
 [0.5 0.  0.5]]


#Gram smidth process

In [35]:
import numpy as np
def proj(y,u):
  # Convert the list of vectors into a numpy array
  y= np.array(y)
  u= np.array(u)
  proj_y=(np.dot(y, u)/np.dot(u, u))*u
  return proj_y
def gram_smidth(vectors):
  V=[]#empty set
  # Convert the list of vectors into a numpy array
  vectors=np.array(vectors)
  for i in range(len(vectors)):
    temp=vectors[i]
    for j in V:
      temp=temp-proj(vectors[i],j)
    V.append(temp)
  return V

A = [[1.0, 1.0, 2.0], [1.0, -1.0, 1.0], [1.0, 2.0, 2.0]]
print(f" The gram smidth process which give the orthogonal basis are \n{gram_smidth(A)}")
#verification
print(f"dot product of first two vectors is \n{np.dot(gram_smidth(A)[0],gram_smidth(A)[1])}")


 The gram smidth process which give the orthogonal basis are 
[array([1., 1., 2.]), array([ 0.66666667, -1.33333333,  0.33333333]), array([ 0.21428571,  0.07142857, -0.14285714])]
dot product of first two vectors is 
2.220446049250313e-16
