# To understand reshape() in python

In [ ]:
import numpy as np
from scipy.linalg import solve
x = np.array([[0, 1, 1],
              [1, 1, 0],
              [1, 0, 1]])
y = np.array([3.65, 1.55, 0])
print("dimension of matrix Y",np.ndim(y))
y1=y.reshape(-1, 1)
print("dimension of matrix Y1",np.ndim(y1))

dimension of matrix Y 1
dimension of matrix Y1 2


#To creat a function "check_Linear Combination" to check Linear combination

In [ ]:
import numpy as np
from scipy.linalg import solve


def check_Linearcombination(A, b):
    # Combine the coefficient matrix A and the constant matrix B
    AB = np.hstack((A, b.reshape(-1, 1)))
    print(AB)

    # To find rank of the matrix
    rank_A = np.linalg.matrix_rank(A)
    print("The rank of a Matrix A",rank_A)
    rank_AB = np.linalg.matrix_rank(AB)
    print("The rank of a Matrix AB",rank_AB)
    print("no of unknowns",len(A))
    if rank_A==rank_AB:
      print(" ")
      if rank_A==len(A):
        print("v can be expressed as LC of A and Which is given as follow")
        x = solve(A, b)
      else:
        x="v can be expressed as LC of A which has infinite way to express it "
    else:
      x="v can not be expressed as LC of A"
    return x
u1 = np.array([0, 1, 1])
u2 = np.array([1, 1, 0])
u3 = np.array([1, 0, 1])
A=[u1,u2,u3]
v = np.array([3.65, 1.55, 0])

check_Linearcombination(A, v)

[[0.   1.   1.   3.65]
 [1.   1.   0.   1.55]
 [1.   0.   1.   0.  ]]
The rank of a Matrix A 3
The rank of a Matrix AB 3
no of unknowns 3
 
v can be expressed as LC of A and Which is given as follow


array([-1.05,  2.6 ,  1.05])

#To creat a function "check_LI or LD" to check LI and LD

In [ ]:
import numpy as np


def check_LI_or_LD(A):

    # To find rank of the matrix
    rank_A = np.linalg.matrix_rank(A)
    print("The rank of a Matrix A",rank_A)
    print("no of unknowns",np.shape(A)[0])
    if rank_A==np.shape(A)[0]:
        x="The given set is L.I"
    else:
        x="The given set is L.D"
    return x
u1 = np.array([0, 1, 0])
u2 = np.array([1, 1, 0])
u3 = np.array([1, 0, 1])
u4 = np.array([1, 0, 1])
A=[u1,u2,u3,u4]

check_LI_or_LD(A)

The rank of a Matrix A 3
no of unknowns 4


'The given set is L.D'

# Linar spans

In [ ]:
import numpy as np

def is_spans(vectors):

    # Let the order of the matrix A is m * n
    rank_A=np.linalg.matrix_rank(vectors)# rank of a matrix A
    print("The rank of a Matrix A",rank_A)

    AB=len(vectors[0])# number of elements in each vector
    print("no of elements in a vector",AB)
    if rank_A==AB:
      x="The given vectors Spans the vector space V"
      return x
    else:
      x="The given vectors does not Spans the vector space V"
      return x

# Example: Checking if the vectors span vector space
vectors = [
    [1, 0, 0],
    [0, 1, 2]
]
print(is_spans(vectors))

print("")

vectors = [
    [1, 0, 0],
    [0, 1, 0],
    [0, 2, 1],
    [0, 2, 1]
]
print(is_spans(vectors))


The rank of a Matrix A 2
no of elements in a vector 3
The given vectors does not Spans the vector space V

The rank of a Matrix A 3
no of elements in a vector 3
The given vectors Spans the vector space V


#Basis for the vector space

In [ ]:
import numpy as np

def is_Basis(vectors):

    # Let the order of the matrix A is m * n
    rank_A=np.linalg.matrix_rank(vectors)# rank of a matrix A
    print("The rank of a Matrix A",rank_A)
    AB=len(vectors[0])# number of elements in each vector
    print("number of elements in each vector",AB)
    n=np.shape(vectors)[0]# number of unkowns
    print("number of unkowns",n)
    if rank_A==AB==n:
      x="The given vectors forms basis"
      return x
    else:
      x="The given vectors does not forms basis form basis for vector space but it is a basia for subspace W of a vectorspace"
      return x

# Example: Checking if the vectors span vector space
vectors = [
    [1, 0, 0],
    [0, 1, 2]
]
print(is_Basis(vectors))

print("")

vectors = [
    [1, 0, 0],
    [0, 1, 0],
    [0, 2, 1]
]

print(is_Basis(vectors))



The rank of a Matrix A 2
number of elements in each vector 3
number of unkowns 2
The given vectors does not forms basis form basis for vector space but it is a basia for subspace W of a vectorspace

The rank of a Matrix A 3
number of elements in each vector 3
number of unkowns 3
The given vectors forms basis


#Four fundamental subspaces

In [ ]:
from sympy import *
M = Matrix([[1, 2, 3, 0, 0], [4, 10, 0, 0, 1]])
print("Matrix M",M)
m,n=M.shape
print(f"There are {m} rows and {n} columns")
MT=M.T
print("Transpose of a Matrix M",MT)
print("")
C_M=M.columnspace()
print("Column space of M\n",C_M)
print("Dimension of Column space of M\n",M.rank())
print("-----------------------------------------")
print("-----------------------------------------")
N_M=M.nullspace()
print("Null space of M\n",N_M)
print("Dimension of Null space of M\n",n-M.rank())
print("-----------------------------------------")
print("-----------------------------------------")
C_MT=MT.columnspace()
print("Row space of M\n",C_MT)
print("Dimension of Row space of M\n",MT.rank())
print("-----------------------------------------")
print("-----------------------------------------")
N_MT=MT.nullspace()
print("Left Null space of M\n",N_MT)
print("Dimension of Left Null space of M\n",m-MT.rank())

Matrix M Matrix([[1, 2, 3, 0, 0], [4, 10, 0, 0, 1]])
There are 2 rows and 5 columns
Transpose of a Matrix M Matrix([[1, 4], [2, 10], [3, 0], [0, 0], [0, 1]])

Column space of M
 [Matrix([
[1],
[4]]), Matrix([
[ 2],
[10]])]
Dimension of Column space of M
 2
-----------------------------------------
-----------------------------------------
Null space of M
 [Matrix([
[-15],
[  6],
[  1],
[  0],
[  0]]), Matrix([
[0],
[0],
[0],
[1],
[0]]), Matrix([
[   1],
[-1/2],
[   0],
[   0],
[   1]])]
Dimension of Null space of M
 3
-----------------------------------------
-----------------------------------------
Row space of M
 [Matrix([
[1],
[2],
[3],
[0],
[0]]), Matrix([
[ 4],
[10],
[ 0],
[ 0],
[ 1]])]
Dimension of Row space of M
 2
-----------------------------------------
-----------------------------------------
Left Null space of M
 []
Dimension of Left Null space of M
 0
